name: Build binaries

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

env:
  GLIBC_VERSION: 2.38

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create directory for storing artefacts
        run: mkdir -p artefacts
      - name: Create Docker image
        run: docker build . --file Dockerfile --tag sgerrand/glibc-builder:$GITHUB_SHA
      - name: Compile glibc package
        run: docker run --rm --env GLIBC_VERSION --env STDOUT=1 sgerrand/glibc-builder:$GITHUB_SHA > artefacts/glibc-bin-$GLIBC_VERSION-0-$(uname -m).tar.gz
      - name: Upload artefacts
        uses: actions/upload-artifact@v3
        with:
          name: artefacts
          path: artefacts/glibc-bin-$GLIBC_VERSION-0-$(uname -m).tar.gz
