name: Build and Upload GLIBC
permissions:
  contents: write
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build-x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Create directory for storing artefacts
        run: mkdir -p artefacts

      - name: Build Docker image
        run: docker build . --tag ruaue/glibc-builder:${{ github.sha }}

      - name: Build glibc package
        run: docker run --rm --env GLIBC_VERSION=2.40 --env STDOUT=1 ruaue/glibc-builder:${{ github.sha }} > artefacts/glibc-bin-2.40-0-$(uname -m).tar.gz

      - name: Upload artefacts
        uses: softprops/action-gh-release@v2
        with:
           tag_name: ${{ github.ref_name }}
           files: |
               artefacts/glibc-bin*.tar.gz
           draft: false
           prerelease: true
           
  build-arm64:
    runs-on: ARM64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Create directory for storing artefacts
        run: mkdir -p artefacts

      - name: Build Docker image
        run: docker build . --tag ruaue/glibc-builder:${{ github.sha }}

      - name: Build glibc package
        run: docker run --rm --env GLIBC_VERSION=2.40 --env STDOUT=1 ruaue/glibc-builder:${{ github.sha }} > artefacts/glibc-bin-2.40-0-$(uname -m).tar.gz

      - name: Upload artefacts
        uses: softprops/action-gh-release@v2
        with:
           tag_name: ${{ github.ref_name }}
           files: |
               artefacts/glibc-bin*.tar.gz
           draft: false
           prerelease: true

